# Generated by Django 4.2.6 on 2026-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitEligibilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('estimated_monthly_min', models.FloatField()),
                ('estimated_monthly_max', models.FloatField()),
                ('confidence', models.CharField(max_length=20)),
                ('enrollment_url', models.URLField()),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'benefit_eligibility',
            },
        ),
    ]
