# Generated by Django 4.2.6 on 2026-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.FloatField()),
                ('pay_date', models.DateField()),
                ('next_pay_date', models.DateField()),
                ('discretionary_available', models.FloatField()),
                ('current_spend', models.FloatField(default=0.0)),
                ('pace_projection', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'paychecks',
            },
        ),
    ]
