# Generated by Django 4.2.6 on 2026-04-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paychecks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'buffer_balances',
            },
        ),
        migrations.CreateModel(
            name='SpendEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_events', to='paychecks.paycheck')),
            ],
            options={
                'db_table': 'spend_events',
            },
        ),
    ]
