# Generated by Django 4.2.6 on 2026-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseholdProfileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gross_income', models.FloatField()),
                ('puma_code', models.CharField(max_length=20)),
                ('tenure', models.CharField(choices=[('OWN', 'Own'), ('RENT', 'Rent')], max_length=4)),
                ('housing_cost', models.FloatField()),
                ('household_size', models.IntegerField()),
                ('filing_status', models.CharField(default='single', max_length=30)),
                ('financial_zone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'household_profiles',
            },
        ),
    ]
